# Generated by Django 2.2.13 on 2022-10-13 08:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='weibo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wuid', models.CharField(max_length=16)),
                ('wnickname', models.CharField(max_length=128)),
                ('wid', models.CharField(max_length=16)),
                ('weibo_link', models.CharField(max_length=128)),
                ('content', models.TextField()),
                ('location', models.TextField()),
                ('publish_time', models.DateField(blank=True, null=True)),
                ('publish_tool', models.CharField(max_length=16)),
                ('like_num', models.PositiveIntegerField(default=0)),
                ('forward_num', models.PositiveIntegerField(default=0)),
                ('comment_num', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
