# Generated by Django 2.2.13 on 2022-10-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeiboScrapy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weibo',
            name='publish_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
